---
dnf_packages_customization:
  # themes
  - adw-gtk3-theme
  - papirus-icon-theme

  # fonts
  - liberation-fonts
  - lohit-assamese-fonts
  - lohit-bengali-fonts
  - lohit-devanagari-fonts
  - lohit-gujarati-fonts
  - lohit-gurmukhi-fonts
  - lohit-kannada-fonts
  - lohit-marathi-fonts
  - lohit-odia-fonts
  - lohit-tamil-fonts
  - lohit-telugu-fonts
  - mozilla-fira-mono-fonts
  - rit-meera-new-fonts
  - rit-rachana-fonts

flatpak_packages_customization:
  # themes
  - org.gtk.Gtk3theme.adw-gtk3
  - org.gtk.Gtk3theme.adw-gtk3-dark
