---
dnf_packages:
  # jdk
  - java-21-openjdk-devel
  - java-21-openjdk-javadoc
  - java-21-openjdk-src
  - java-21-openjdk-jmods

  # mvn
  - maven

flatpak_packages:
  - com.jetbrains.IntelliJ-IDEA-Community
  - com.getpostman.Postman
  - org.pgadmin.pgadmin4
