---
vscode_extensions:
  DEFAULT:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    - github.copilot
    - github.copilot-chat
    - ms-azuretools.vscode-containers
    - pkief.material-icon-theme
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - sonarsource.sonarlint-vscode
    - visualstudioexptteam.intellicode-api-usage-examples
    - visualstudioexptteam.vscodeintellicode
  JAVA:
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    - github.copilot
    - github.copilot-chat
    - josevseb.google-java-format-for-vs-code
    - ms-azuretools.vscode-containers
    - pkief.material-icon-theme
    - redhat.java
    - redhat.vscode-microprofile
    - redhat.vscode-quarkus
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - renesaarsoo.sql-formatter-vsc
    - sonarsource.sonarlint-vscode
    - visualstudioexptteam.intellicode-api-usage-examples
    - visualstudioexptteam.vscodeintellicode
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
  PYTHON:
    - esbenp.prettier-vscode
    - foxundermoon.shell-format
    - github.copilot
    - github.copilot-chat
    - ms-azuretools.vscode-containers
    - ms-python.black-formatter
    - ms-python.debugpy
    - ms-python.isort
    - ms-python.python
    - ms-python.vscode-pylance
    - pkief.material-icon-theme
    - redhat.ansible
    - redhat.vscode-xml
    - redhat.vscode-yaml
    - sonarsource.sonarlint-vscode
    - visualstudioexptteam.intellicode-api-usage-examples
    - visualstudioexptteam.vscodeintellicode
