---
- name: Log installing packages
  ansible.builtin.debug:
    msg: "{{ dnf_install_packages }}"

- name: Install DNF packages
  ansible.builtin.dnf5:
    name: "{{ dnf_install_packages }}"
    state: present
  become: true
  when: (dnf_install_packages | default([])) | length > 0
