---
- name: Install Chromium Flatpak
  community.general.flatpak:
    name: "org.chromium.Chromium"
    remote: flathub
    executable: /usr/bin/flatpak
    method: system
    state: present
  become: false

- name: Grant access for creating app shortcuts
  ansible.builtin.command: >
    flatpak override --user \
      --filesystem=~/.local/share/applications \
      --filesystem=~/.local/share/icons \
      org.chromium.Chromium
  changed_when: true

- name: Grant access to home directory
  ansible.builtin.command: >
    flatpak override --user \
      --filesystem=home \
      org.chromium.Chromium
  changed_when: true

- name: Grant access to dbus
  ansible.builtin.command: >
    flatpak override --user --socket=session-bus org.chromium.Chromium
    flatpak override --user --socket=system-bus org.chromium.Chromium
  changed_when: true

- name: Inherit Wayland socket
  ansible.builtin.command: >
    flatpak override --user --socket=inherit-wayland-socket com.google.Chrome
  changed_when: true

- name: Enable Google APIs for Chromium Flatpak
  # source - https://stackoverflow.com/a/78191462
  ansible.builtin.shell: |
    flatpak override --user \
      --env=GOOGLE_DEFAULT_CLIENT_ID=77185425430.apps.googleusercontent.com \
      --env=GOOGLE_DEFAULT_CLIENT_SECRET=OTJgUOQcT7lO7GsGZq2G4IlT \
      org.chromium.Chromium
  changed_when: true
