---
- name: Remove Ptyxis existing profiles
  ansible.builtin.shell: |
    dconf reset -f /org/gnome/Ptyxis/Profiles/
  changed_when: true

- name: Load Ptyxis settings
  ansible.builtin.shell: |
    dconf load /org/gnome/Ptyxis/ < {{ role_path }}/files/preferences.conf
  changed_when: true
