---
all:
  children:
    laptop:
      hosts:
        home_laptop:
          ansible_host: localhost
          ansible_connection: local

    server:
      hosts:
        server_yankee:
          ansible_host: yankee
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/workMachineAccess"

        server_zulu_98:
          ansible_host: zulu
          ansible_user: root
          ansible_port: 2298
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/workMachineAccess"

        server_zulu_99:
          ansible_host: zulu
          ansible_user: root
          ansible_port: 2299
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/workMachineAccess"
