---
all:
  children:
    laptop:
      hosts:
        home_laptop:
          ansible_host: localhost
          ansible_connection: local

    server:
      hosts:
        server_yankee:
          ansible_host: yankee.userful.ca
          ansible_user: root
          ansible_port: 22
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/workMachineAccess"

        server_canuck:
          ansible_host: zulu.userful.ca
          ansible_user: root
          ansible_port: 2298
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/workMachineAccess"
