---
- name: Create VS Code profile "{{ profile }}"
  ansible.builtin.shell: |
    code --profile "{{ profile }}" --new-window &
    sleep 5
    pkill -f "code --profile"
  args:
    executable: /bin/bash
  when: profile != 'DEFAULT'
  changed_when: false
  delegate_to: localhost

- name: Install extensions for profile "{{ profile }}"
  ansible.builtin.shell: |
    code --install-extension {{ item }}{% if profile != 'DEFAULT' %} --profile {{ profile }}{% endif %}
  args:
    executable: /bin/bash
  loop: "{{ vscode_extensions[profile] }}"
  loop_control:
    label: "{{ item }}"
  register: vscode_extensions_install_output
  changed_when: "'already installed' not in vscode_extensions_install_output.stdout"
  failed_when: vscode_extensions_install_output.rc != 0
  delegate_to: localhost
