---
- name: Log removing packages
  ansible.builtin.debug:
    msg: "{{ unwanted_packages }}"

- name: Remove DNF packages
  ansible.builtin.dnf5:
    name: "{{ unwanted_packages }}"
    state: absent
    allowerasing: true
  become: true
  when: (unwanted_packages | default([])) | length > 0

- name: Log removing fonts
  ansible.builtin.debug:
    msg: "{{ fonts_to_remove }}"

- name: Remove fonts
  ansible.builtin.dnf5:
    name: "{{ fonts_to_remove }}"
    state: absent
    allowerasing: true
  become: true
  when: (fonts_to_remove | default([])) | length > 0
