---
- name: Log removing packages
  ansible.builtin.debug:
    msg: "{{ dnf_packages_cleanup }}"

- name: Remove DNF packages
  ansible.builtin.dnf:
    name: "{{ dnf_packages_cleanup }}"
    state: absent
    allowerasing: true
  become: true
  when: (dnf_packages_cleanup | default([])) | length > 0

- name: DNF Autoremove
  ansible.builtin.dnf:
    autoremove: true
  become: true
  when: (dnf_packages_cleanup | default([])) | length > 0
