---
- name: Log removing packages
  ansible.builtin.debug:
    msg: "{{ dnf_packages }}"

- name: Remove DNF packages
  ansible.builtin.dnf5:
    name: "{{ dnf_packages }}"
    state: absent
    allowerasing: true
  become: true
  when: (dnf_packages | default([])) | length > 0
