---
- name: Add Windsurf GPG key
  ansible.builtin.rpm_key:
    key: https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/yum/RPM-GPG-KEY-windsurf
    state: present
  become: true

- name: Add Windsurf repository
  ansible.builtin.yum_repository:
    name: windsurf
    description: "Windsurf"
    baseurl: https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/yum/repo/
    enabled: true
    gpgcheck: true
    gpgkey: https://windsurf-stable.codeiumdata.com/wVxQEIWkwPUEAGf3/yum/RPM-GPG-KEY-windsurf
  become: true

- name: Install Windsurf
  ansible.builtin.dnf:
    name: windsurf
    state: present
  become: true

- name: Ensure Windsurf config directory exists
  ansible.builtin.file:
    path: ~/.config/Windsurf/User
    state: directory
    mode: "0755"

- name: Copy Windsurf settings
  ansible.builtin.copy:
    src: settings.jsonc
    dest: ~/.config/Windsurf/User/settings.json
    mode: "0644"

- name: Copy Windsurf keybindings
  ansible.builtin.copy:
    src: keybindings.jsonc
    dest: ~/.config/Windsurf/User/keybindings.json
    mode: "0644"

- name: Load vscode_extensions var
  ansible.builtin.include_vars:
    file: ../vars/extensions.yaml

- name: Install extensions for each profile
  ansible.builtin.include_tasks: install_extensions.yaml
  loop: "{{ vscode_extensions.keys() | list }}"
  loop_control:
    loop_var: profile
