---
- name: Load Nautilus settings
  ansible.builtin.shell: |
    dconf load /org/gnome/nautilus/preferences/ < {{ role_path }}/files/preferences.conf
  changed_when: true

- name: Load file chooser settings
  ansible.builtin.shell: |
    dconf load /org/gtk/gtk4/settings/file-chooser/ < {{ role_path }}/files/filechooser.conf
  changed_when: true
