---
- name: Log install apps
  ansible.builtin.debug:
    msg: "{{ flatpak_packages }}"

- name: Install apps
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    remote: flathub
    executable: /usr/bin/flatpak
    method: system
    state: present
  become: false
  when: (flatpak_packages | default([])) | length > 0
