---
- name: Install Google Chrome Flatpak
  community.general.flatpak:
    name: "com.google.Chrome"
    remote: flathub
    executable: /usr/bin/flatpak
    method: system
    state: present
  become: false

- name: Grant access for creating app shortcuts
  ansible.builtin.command: >
    flatpak override --user \
      --filesystem=~/.local/share/applications \
      --filesystem=~/.local/share/icons \
      com.google.Chrome
  changed_when: true

- name: Grant access to home directory
  ansible.builtin.command: >
    flatpak override --user \
      --filesystem=home \
      com.google.Chrome
  changed_when: true

- name: Grant access to dbus
  ansible.builtin.command: >
    flatpak override --user --socket=session-bus --socket=system-bus com.google.Chrome
  changed_when: true

- name: Inherit Wayland socket
  ansible.builtin.command: >
    flatpak override --user --socket=inherit-wayland-socket com.google.Chrome
  changed_when: true
