---
- name: Installing JDK
  ansible.builtin.dnf5:
    name: "{{ jdk_dnf_packages }}"
    state: present
  become: true
  when: (jdk_dnf_packages | default([])) | length > 0

- name: Installing Maven
  ansible.builtin.dnf5:
    name: "{{ maven_dnf_packages }}"
    state: present
  become: true
  when: (maven_dnf_packages | default([])) | length > 0

- name: Installing IntelliJ IDEA Flatpak
  community.general.flatpak:
    name: "{{ ide_flatpak_packages }}"
    remote: flathub
    executable: /usr/bin/flatpak
    method: system
    state: present
  become: false
  when: (ide_flatpak_packages | default([])) | length > 0
