---
- name: Copy .bashrc
  ansible.builtin.copy:
    src: .bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
    mode: "0644"

- name: Copy .bashrc-server
  ansible.builtin.copy:
    src: .bashrc-server
    dest: "{{ ansible_env.HOME }}/.bashrc-server"
    mode: "0644"

- name: Copy .gitconfig
  ansible.builtin.copy:
    src: .gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: "0644"

- name: Copy .gitconfig-work
  ansible.builtin.copy:
    src: .gitconfig-work
    dest: "{{ ansible_env.HOME }}/.gitconfig-work"
    mode: "0644"

- name: Copy .inputrc
  ansible.builtin.copy:
    src: .inputrc
    dest: "{{ ansible_env.HOME }}/.inputrc"
    mode: "0644"

- name: Copy .vimrc
  ansible.builtin.copy:
    src: .vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: "0644"

- name: Copy all bash scripts
  ansible.builtin.copy:
    src: scripts/
    dest: "{{ ansible_env.HOME }}/"
    mode: "0755"

- name: Ensure bash completion directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"
    state: directory
    mode: "0755"

- name: Copy bash completion files
  ansible.builtin.copy:
    src: bash_completion/
    dest: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions/"
    mode: "0644"

- name: Ensure cockpit socket config directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/cockpit.socket.d/
    state: directory
    mode: "0755"

- name: Change cockpit port
  ansible.builtin.copy:
    src: cockpit_port.conf
    dest: /etc/systemd/system/cockpit.socket.d/listen.conf
    mode: "0644"

- name: Restart cockpit service
  ansible.builtin.systemd:
    daemon_reload: true
    name: cockpit.socket
    state: restarted
    enabled: true
  become: true
