---
- name: Download WebStorm
  ansible.builtin.get_url:
    url: https://download-cdn.jetbrains.com/webstorm/WebStorm-2025.1.2.tar.gz
    dest: "{{ ansible_env.HOME }}/webstorm.tar.gz"
    mode: "0644"

- name: Extract WebStorm
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/webstorm.tar.gz"
    dest: "{{ ansible_env.HOME }}/"
    remote_src: true
  become: false

- name: Remove downloaded WebStorm archive
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/webstorm.tar.gz"
    state: absent

- name: Rename extracted WebStorm directory
  ansible.builtin.shell: mv {{ ansible_env.HOME }}/WebStorm-* /opt/webstorm
  args:
    removes: "{{ ansible_env.HOME }}/WebStorm-*"
    creates: /opt/webstorm
  become: true

- name: Modify WebStorm config path
  ansible.builtin.lineinfile:
    path: /opt/webstorm/bin/idea.properties
    regexp: "^# idea.config.path="
    line: "idea.config.path=${user.home}/.config/jetbrains/webstorm/config"
    state: present
    backrefs: true
  become: false
  register: result

- name: Modify WebStorm cache path
  ansible.builtin.lineinfile:
    path: /opt/webstorm/bin/idea.properties
    regexp: "^# idea.system.path="
    line: "idea.system.path=${user.home}/.config/jetbrains/webstorm/system"
    state: present
    backrefs: true
  become: false
  register: result

- name: Modify WebStorm plugins path
  ansible.builtin.lineinfile:
    path: /opt/webstorm/bin/idea.properties
    regexp: "^# idea.plugins.path="
    line: "idea.plugins.path=${idea.config.path}/plugins"
    state: present
    backrefs: true
  become: false
  register: result

- name: Modify WebStorm log path
  ansible.builtin.lineinfile:
    path: /opt/webstorm/bin/idea.properties
    regexp: "^# idea.log.path="
    line: "idea.log.path=${idea.config.path}/log"
    state: present
    backrefs: true
  become: false
  register: result

- name: Copy WebStorm VM options
  ansible.builtin.copy:
    src: idea64.vmoptions
    dest: /opt/webstorm/bin/idea64.vmoptions
    mode: "0644"
  become: true

- name: Create WebStorm desktop entry
  ansible.builtin.copy:
    src: jetbrains-webstorm.desktop
    dest: /usr/share/applications/jetbrains-webstorm.desktop
    mode: "0644"
  become: true

- name: Copy all settings
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/jetbrains/webstorm/"
    mode: "0644"
  become: false

- name: Load webstorm_plugins var
  ansible.builtin.include_vars:
    file: ../vars/plugins.yaml

- name: Install plugins
  ansible.builtin.shell: |
    /opt/webstorm/bin/webstorm installPlugins {{ item }}
  args:
    executable: /bin/bash
  loop: "{{ webstorm_plugins }}"
  register: plugin_install_result
  changed_when: "'already installed' not in plugin_install_result.stdout"
  become: false
