#!/usr/bin/env bash

set -euo pipefail

block() {
    echo -e "\n\n"
    echo "$@"
    echo "[ERROR] Commit blocked."
    exit 1
}

lint_checks() {
    local staged
    staged=$(git diff --name-only --cached --exit-code -- '*.y*ml')
    ret=$?
    if [ $ret -eq 0 ]; then
        return 0
    fi

    (ansible-lint -q) || block "[ERROR] Ansible lint failed."

    for file in $(find playbooks -name "*.yaml"); do
        ansible-playbook --syntax-check "$file" 1>/dev/null || block "[ERROR] Ansible lint failed."
    done
}

(lint_checks) || exit $?
