---
- name: Load screenshot keybindings
  ansible.builtin.shell: |
    dconf load /org/gnome/shell/keybindings/ < {{ role_path }}/files/screenshot.conf
  changed_when: true

- name: Remove existing media keys keybindings
  ansible.builtin.shell: |
    dconf reset -f /org/gnome/settings-daemon/plugins/media-keys/
  changed_when: true

- name: Load media keys keybindings
  ansible.builtin.shell: |
    dconf load /org/gnome/settings-daemon/plugins/media-keys/ < {{ role_path }}/files/mediakeys.conf
  changed_when: true

- name: Load switch windows keybindings
  ansible.builtin.shell: |
    dconf load /org/gnome/desktop/wm/keybindings/ < {{ role_path }}/files/switchWindows.conf
  changed_when: true
