---
- name: Download IntelliJ IDEA
  ansible.builtin.get_url:
    url: https://download-cdn.jetbrains.com/idea/ideaIC-2025.1.1.1.tar.gz
    dest: "{{ ansible_env.HOME }}/intellij-idea.tar.gz"
    mode: "0644"

- name: Extract IntelliJ IDEA
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME }}/intellij-idea.tar.gz"
    dest: "{{ ansible_env.HOME }}/"
    remote_src: true
  become: false

- name: Removed downloaded IntelliJ IDEA archive
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/intellij-idea.tar.gz"
    state: absent

- name: Rename extracted IntelliJ IDEA directory
  ansible.builtin.shell: mv {{ ansible_env.HOME }}/idea-IC-* /opt/intellij-idea
  args:
    removes: "{{ ansible_env.HOME }}/idea-IC-*"
    creates: /opt/intellij-idea
  become: true

- name: Modify IntelliJ config path
  ansible.builtin.lineinfile:
    path: /opt/intellij-idea/bin/idea.properties
    regexp: "^# idea.config.path="
    line: "idea.config.path=${user.home}/.config/jetbrains/intellij-idea/config"
    state: present
    backrefs: true
  become: false
  register: result

- name: Modify IntelliJ cache path
  ansible.builtin.lineinfile:
    path: /opt/intellij-idea/bin/idea.properties
    regexp: "^# idea.system.path="
    line: "idea.system.path=${user.home}/.config/jetbrains/intellij-idea/system"
    state: present
    backrefs: true
  become: false
  register: result

- name: Modify IntelliJ plugins path
  ansible.builtin.lineinfile:
    path: /opt/intellij-idea/bin/idea.properties
    regexp: "^# idea.plugins.path="
    line: "idea.plugins.path=${idea.config.path}/plugins"
    state: present
    backrefs: true
  become: false
  register: result

- name: Modify IntelliJ log path
  ansible.builtin.lineinfile:
    path: /opt/intellij-idea/bin/idea.properties
    regexp: "^# idea.log.path="
    line: "idea.log.path=${idea.config.path}/log"
    state: present
    backrefs: true
  become: false
  register: result

- name: Copy IntelliJ VM options
  ansible.builtin.copy:
    src: idea64.vmoptions
    dest: /opt/intellij-idea/bin/idea64.vmoptions
    mode: "0644"
  become: true

- name: Create IntelliJ IDEA desktop entry
  ansible.builtin.copy:
    src: jetbrains-intellij-idea.desktop
    dest: /usr/share/applications/jetbrains-intellij-idea.desktop
    mode: "0644"
  become: true

- name: Copy all settings
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/jetbrains/intellij-idea/"
    mode: "0644"
  become: false
