---
- name: Install Microsoft Edge Flatpak
  community.general.flatpak:
    name: "com.microsoft.Edge"
    remote: flathub
    executable: /usr/bin/flatpak
    method: system
    state: present
  become: false

- name: Grant access for creating app shortcuts
  ansible.builtin.command: >
    flatpak override --user \
      --filesystem=~/.local/share/applications \
      --filesystem=~/.local/share/icons
      com.microsoft.Edge
  changed_when: true

- name: Grant access to home directory
  ansible.builtin.command: >
    flatpak override --user \
      --filesystem=home \
      com.microsoft.Edge
  changed_when: true

- name: Grant access to dbus
  ansible.builtin.command: >
    flatpak override --user --socket=session-bus com.microsoft.Edge
    flatpak override --user --socket=system-bus com.microsoft.Edge
  changed_when: true

- name: Inherit Wayland socket
  ansible.builtin.command: >
    flatpak override --user --socket=inherit-wayland-socket com.microsoft.Edge
  changed_when: true
