---
- name: Remove existing app folders
  ansible.builtin.shell: |
    dconf reset -f /org/gnome/desktop/app-folders/
  changed_when: true

- name: Setup app folders
  ansible.builtin.shell: |
    dconf load /org/gnome/desktop/app-folders/ < {{ role_path }}/files/appFolders.conf
  changed_when: true

- name: Setup app picker layout
  ansible.builtin.shell: |
    dconf write /org/gnome/shell/app-picker-layout "$(cat '{{ role_path }}/files/appPicker.conf')"
  changed_when: true

- name: Setup favorites
  ansible.builtin.shell: |
    dconf write /org/gnome/shell/favorite-apps "$(cat '{{ role_path }}/files/favorites.conf')"
  changed_when: true
