---
- name: Update logind.conf
  ansible.builtin.include_tasks: logind_conf.yaml

- name: Update app layout
  ansible.builtin.include_tasks: app_layout.yaml

- name: Update mutter settings
  ansible.builtin.include_tasks: mutter.yaml

- name: Update desktop interface settings
  ansible.builtin.include_tasks: desktop_interface.yaml

- name: Include backgrounds directory
  ansible.builtin.include_tasks: wallpaper.yaml

- name: Update touchpad settings
  ansible.builtin.include_tasks: touchpad.yaml

- name: Disable wellbeing
  ansible.builtin.include_tasks: wellbeing.yaml

- name: Enable night light
  ansible.builtin.include_tasks: night_light.yaml
