---
- name: Ensure HandleLidSwitch is set to ignore
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?HandleLidSwitch="
    line: "HandleLidSwitch=ignore"
    state: present
    backrefs: true
  become: true

- name: Ensure LidSwitchIgnoreInhibited is set to yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?LidSwitchIgnoreInhibited="
    line: "LidSwitchIgnoreInhibited=yes"
    state: present
    backrefs: true
  become: true

- name: Setup app folders
  ansible.builtin.shell: |
    dconf load /org/gnome/desktop/app-folders/ < {{ role_path }}/files/appFolders.conf
  changed_when: true

- name: Setup mutter
  ansible.builtin.shell: |
    dconf load /org/gnome/mutter/ < {{ role_path }}/files/mutter.conf
  changed_when: true

- name: Load Gnome Tweaks settings
  ansible.builtin.shell: |
    dconf load /org/gnome/desktop/interface/ < {{ role_path }}/files/tweaks.conf
  changed_when: true
