---
- name: Ensure HandleLidSwitch is set to ignore
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?HandleLidSwitch="
    line: "HandleLidSwitch=ignore"
    state: present
    backrefs: true
  become: true
  ignore_errors: true
  register: result

- name: Ensure LidSwitchIgnoreInhibited is set to yes
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    regexp: "^#?LidSwitchIgnoreInhibited="
    line: "LidSwitchIgnoreInhibited=yes"
    state: present
    backrefs: true
  become: true
  ignore_errors: true
  register: result

- name: Remove existing app folders
  ansible.builtin.shell: |
    dconf reset -f /org/gnome/desktop/app-folders/
  changed_when: true

- name: Setup app folders
  ansible.builtin.shell: |
    dconf load /org/gnome/desktop/app-folders/ < {{ role_path }}/files/appFolders.conf
  changed_when: true

- name: Setup app picker layout
  ansible.builtin.shell: |
    dconf write /org/gnome/shell/app-picker-layout "$(cat '{{ role_path }}/files/appPicker.conf')"
  changed_when: true

- name: Setup favorites
  ansible.builtin.shell: |
    dconf write /org/gnome/shell/favorite-apps "$(cat '{{ role_path }}/files/favorites.conf')"
  changed_when: true

- name: Setup mutter
  ansible.builtin.shell: |
    dconf load /org/gnome/mutter/ < {{ role_path }}/files/mutter.conf
  changed_when: true

- name: Load Gnome Tweaks settings
  ansible.builtin.shell: |
    dconf load /org/gnome/desktop/interface/ < {{ role_path }}/files/tweaks.conf
  changed_when: true

- name: Update background directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/backgrounds"
    state: link
    src: "{{ ansible_env.HOME }}/Pictures/Wallpapers"
  changed_when: true
