---
- name: UI Customization
  hosts: laptop
  vars_files:
    - ../group_vars/customization.yaml
  roles:
    - dnf
    - flatpak
    - dotfiles
    - cursors
    - keybindings
    - settings
    - gnome_text_editor
    - nautilus
