---
- name: UI Customization
  hosts: laptop
  vars_files:
    - ../group_vars/customization.yaml
  roles:
    - role: dnf
      dnf_packages: "{{ dnf_packages_customization }}"
    - role: flatpak
      flatpak_packages: "{{ flatpak_packages_customization }}"
    - role: dotfiles
    # - role: cursors
    # - role: keybindings
    # - role: settings
    - role: gnome_text_editor
    - role: nautilus
