---
- name: Java development environment
  hosts: laptop
  vars_files:
    - ../group_vars/java.yaml
  roles:
    - role: dnf
      dnf_packages: "{{ dnf_packages_java }}"
    - role: flatpak
      flatpak_packages: "{{ flatpak_packages_java }}"
    - role: intellij_idea
