---
- name: Additional tools installation
  hosts: laptop
  vars_files:
    - ../group_vars/tools.yaml
  roles:
    - role: dnf
      dnf_packages: "{{ dnf_packages_tools }}"
    - role: flatpak
      flatpak_packages: "{{ flatpak_packages_tools }}"
