---
- name: Download Google Chrome
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    dest: /tmp/google-chrome-stable_current_x86_64.rpm
    mode: "0644"

- name: Install Google Chrome
  ansible.builtin.dnf5:
    name: /tmp/google-chrome-stable_current_x86_64.rpm
    state: present
  become: true
