flatpak_apps:
  # configuration
  - com.github.tchx84.Flatseal

  # development
  - com.getpostman.Postman
  - org.pgadmin.pgadmin4

  # tools
  - io.gitlab.liferooter.TextPieces
  - org.gnome.dspy
  - org.nickvision.tagger
  - org.nickvision.tubeconverter
  - org.remmina.Remmina

  # misc
  - org.telegram.desktop
