---
name: CI

on:
  push:
    paths:
      - "**.yaml"
      - "**.yml"
      - "**.md"
      - "**.sh"
      - "**.py"
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: ansible-lint

      - name: Playbook Syntax Check
        run: |
          for file in $(find playbooks -name "*.yaml"); do
            ansible-playbook --syntax-check "$file" || exit 1
          done
