---
- name: Load gnome-terminal settings
  ansible.builtin.shell: |
    dconf load /org/gnome/terminal/legacy/profiles:/ < {{ role_path }}/files/profiles.conf
  changed_when: true

- name: Load terminal keybindings
  ansible.builtin.shell: |
    dconf load /org/gnome/terminal/legacy/keybindings/ < {{ role_path }}/files/terminal.conf
  changed_when: true
