---
- name: Log install fonts
  ansible.builtin.debug:
    msg: "{{ fonts_to_install }}"

- name: Install fonts
  ansible.builtin.dnf5:
    name: "{{ fonts_to_install }}"
    state: present
  become: true
  when: (fonts_to_install | default([])) | length > 0
